### ISSUE TITLE
Show an error if useCustomHieWrapper is true and useCustomHieWrapperPath is not set

### ISSUE THREAD

**Issue by cblp** [alanz/vscode-hie-server#101]
```
Starting client failed
Error: Unsupported server configuration {
    "run": {
        "command": "",
        "transport": 0,
        "args": []
    },
    "debug": {
        "command": "",
        "transport": 0,
        "args": [
            "-d",
            "-l",
            "/tmp/hie.log"
        ]
    }
}
	at LanguageClient.createMessageTransports (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/node_modules/vscode-languageclient/lib/main.js:337:31)
	at LanguageClient.createConnection (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/node_modules/vscode-languageclient/lib/client.js:1854:21)
	at LanguageClient.resolveConnection (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/node_modules/vscode-languageclient/lib/client.js:1697:44)
	at LanguageClient.start (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/node_modules/vscode-languageclient/lib/client.js:1628:14)
	at activateHieNoCheck (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/out/src/extension.js:194:16)
	at /Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/out/src/extension.js:75:17
	at Generator.next (<anonymous>)
	at fulfilled (/Users/cblp/.vscode/extensions/alanz.vscode-hie-server-0.0.14/out/src/extension.js:4:58)
	at <anonymous>
```

**Comment by dreamkidd** [comment]
I got same error like u 
```
Starting client failed
Error: Unsupported server configuration {
    "run": {
        "command": "",
        "transport": 0,
        "args": []
    },
    "debug": {
        "command": "",
        "transport": 0,
        "args": []
    }
}
	at _getServerWorkingDir.then.serverWorkingDir (/Users/zhangyang/.vscode/extensions/alanz.vscode-hie-server-0.0.24/node_modules/vscode-languageclient/lib/main.js:356:35)
	at <anonymous>

```

**Comment by alkthegit** [comment]
I was getting the same error because previously I set "Use Custom Hie Wrapper" parameter to ON in the HIE extension settings.
When I switched it off again, it started working.

**Comment by chrismwendt** [comment]
If you set

```json
  "languageServerHaskell.enableHIE": true
```

you also have to set

```json
  "languageServerHaskell.useCustomHieWrapperPath": "~/wrapper-in-home.sh"
```

(from https://github.com/alanz/vscode-hie-server#custom-wrapper)

This extension could detect that invalid configuration and display a message.

**Comment by jneira** [comment]
I've changed the title to cover the last one suggestion from @chrismwendt

**Comment by jneira** [comment]
The wrapper has been removed in the last version, so the issue is not applicable
