### ISSUE TITLE
Conflict with Vim extension on NixOS

### ISSUE THREAD

**Issue by geraldus** [alanz/vscode-hie-server#16]
Running `vscode-hie-server` with `Vim` makes impossible to edit files.  E.g. it is not possible to move using <kbd>H</kbd> <kbd>J</kbd> <kbd>K</kbd> <kbd>L</kbd>, change mode other to `NORMAL`, it looks like all keyboard input is ignored.  Disabling `Vim` plugin restores normal behaviour.

**Comment by alanz** [comment]
Using `vscode 1.16.0`, `Vim 0.10.0` and `vscode-hie-server 0.0.2` I get the expected behaviour
 for `h j k l H L`

**Comment by alanz** [comment]
Using `vscode 1.16.0`, `Vim 0.10.0` and `vscode-hie-server 0.0.2` I get the expected behaviour
 for `h j k l H L`

**Comment by geraldus** [comment]
Hmm... I'm on NixOS.  I have installed HIE server via Marketplace.  Seems it's not working at all:

```
Error: libxkbfile.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (file:///nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/out/vs/loader.js:4:10954)
    at NativeBinding._init (/nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/native-keymap/index.js:15:22)
    at NativeBinding.getCurrentKeyboardLayout (/nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/native-keymap/index.js:28:10)
NativeBinding.getCurrentKeyboardLayout @ /nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/nat…:31
/nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/nat…:22 TypeError: Cannot read property 'getKeyMap' of null
    at NativeBinding.getKeyMap (/nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/nat…:20)
    at Object.exports.getKeyMap (/nix/store/p5zqbvc6qs80ab35gnqssy2priypj22j-vscode-1.16.0/lib/vscode/resources/app/node_modules/nat…:58)
    at e.getKeyboardMapper (keybindingService.ts:72)
    at new t (keybindingService.ts:289)
    at t.create (types.ts:168)
    at t._createInstance (instantiationService.ts:162)
    at t.createInstance (instantiationService.ts:78)
    at e.initServices (workbench.ts:548)
    at e.startup (workbench.ts:288)
    at e.createContents (shell.ts:168)
```
Looks like some node modules are missing.

**Comment by alanz** [comment]
Perhaps try to find where it installed it and issue the appropriate `npm ...` command. Whatever it is.

I can't help with nixos stuff, unfortunately.

**Comment by alanz** [comment]
You could try installing it like this too: https://github.com/alanz/haskell-ide-engine#using-hie-with-vscode

**Comment by geraldus** [comment]
I have tried that method before and after I opened this issue and all time I get same behaviour.

**Comment by Tehnix** [comment]
I don't think this is an issue with this extension, but something is wrong in the way the extension got installed perhaps? VSCode should handle all node modules that needs installed.

I'm closing this, but let me know if you're still having the problem, and then we can reopen it.
