### ISSUE TITLE
HLS: Error connection got disposed

### ISSUE THREAD

**Issue by RobertLucian** [alanz/vscode-hie-server#493]
#### Description

I'm new to Haskell. Just trying to install this extension with HLS and I keep getting the following error for any of the 1.6.x/1.7.x versions of this extension. The following error gets repeated 5 times before it gives us trying to restart the server.

```
[2021-10-26 19:48:17.967] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:247:58221)
	at Object.dispose (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:78088)
	at E.handleConnectionClosed (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:78300)
	at E.handleConnectionClosed (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:247:11275)
	at t (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:76393)
	at invoke (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:155272)
	at o.fire (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:156033)
	at J (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:247:47583)
	at invoke (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:155272)
	at o.fire (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:1:156033)
	at fireClose (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:247:37656)
	at Socket.<anonymous> (/Users/robert/.vscode/extensions/haskell.haskell-1.6.1/dist/extension.js:247:39236)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

Before the above error is shown, I'm also getting the following warning (not sure how relevant this is though):

```
[2021-10-26 19:56:47.476] [renderer1] [error] [Extension Host] (node:79987) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
```

* Using HLS 8.10.7 (1.4.0) on GHCup 0.1.17.2 and Cabal 3.4.1.0.
* Has been tested with both HLS executable path set and not set.

VSCode's about:
```
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
---

Does anyone have an idea what is wrong with this picture? I can hep further diagnose this at someone's request.

**Comment by willbasky** [comment]
I faced the same error when I try to evaluate a statement with `-- >>>`.

HLS debug output:
[hls.log](https://github.com/haskell/vscode-haskell/files/8547380/hls.log)
Extension_host log:
[extension_host.log](https://github.com/haskell/vscode-haskell/files/8547381/extension_host.log)
Window log:
[window.log](https://github.com/haskell/vscode-haskell/files/8547382/window.log)

**Comment by fendor** [comment]
Is this still relevant?

I am tending to close this and wait for a new bug report.

**Comment by willbasky** [comment]
It took place 8 days ago, I am not sure it has gone already.

**Comment by fendor** [comment]
@willbasky You should report your particular issue to the main HLS repo, since what you describe is HLS segfaulting. Not much we can do about it in the vscode extension.

(BTW, no idea why this issue was suddenly open on my screen)

**Comment by fendor** [comment]
Closed because there is nothing we can do. Issue of HLS main repo.
