### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by MuratOzsoyler** [alanz/vscode-hie-server#68]
Windows 10
VCode 1.22.2
Haskell Language Server 0.0.15
Haskell Syntax Highlighting 2.4.0

Stack (version 1.6.5) project, resolver: nightly-2018-04-09.

When opened with no editor tabs, in Developer Tools console:
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] No editors associated with document: c:\Users\zmtemp\Desktop\haskell\gtk\haskell-gi\examples\advanced\Cairo.hs

[Extension Host] TypeError: Cannot read property 'document' of undefined
	at Object.registerCommand (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\commands\showType.js:78:58)
	at activateHieNoCheck (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:185:36)
	at C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:75:17
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:4:58)
	at <anonymous>
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
```

After a Haskell source opened this message appears:
```
[Extension Host] Error: command 'hie.commands.insertType' already exists
	at e.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:594:33)
	at Object.registerTextEditorCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:876)
	at Object.registerCommand (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\commands\insertType.js:9:39)
	at activateHieNoCheck (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:184:60)
	at C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:75:17
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.15\out\src\extension.js:4:58)
	at <anonymous>
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:395
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

No lint, no suggestions, no intellisense.

I feel this may be due to the version of GHC (8.4.1). If so, can we solve this problem?

**Comment by Tehnix** [comment]
I think this is actually a problem in VSCode after support for multi-root workspaces were added. I'll look into it.

**Comment by MuratOzsoyler** [comment]
Thank you for responding. I should mention that the project is not multi-root.

**Comment by MuratOzsoyler** [comment]
@Tehnix Thank you for your effort.

I've just tried the new version. This time there is no error messages. But still no intellisense and no suggestions. Just `Loading...` indicator...

In the first load hlint works for once but if you solve the indicated error or introduce new errors, messages do not change till the next re-start.

**Comment by Tehnix** [comment]
Do you get any output in the output tab when selecting `Haskell HIE (...)`?

**Comment by MuratOzsoyler** [comment]
There is not an option for `Haskell HIE`. But when I select `Log (Extension host)` following lines are at the bottom of the log:
```
[2018-04-17 21:38:06.087] [exthost1] [info] ExtensionService#_doActivateExtension justusadam.language-haskell {"startup":false,"activationEvent":"onLanguage:haskell"}
[2018-04-17 21:38:06.087] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\zmtemp\.vscode\extensions\justusadam.language-haskell-2.4.0\out\src\extension
[2018-04-17 21:38:06.116] [exthost1] [info] ExtensionService#_doActivateExtension alanz.vscode-hie-server {"startup":false,"activationEvent":"onLanguage:haskell"}
[2018-04-17 21:38:06.116] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\zmtemp\.vscode\extensions\alanz.vscode-hie-server-0.0.16\out\src\extension
```

**Comment by MuratOzsoyler** [comment]
I've just set `"languageServerHaskell.trace.server": "verbose"` but can't recognize where to see the trace. Nothing changed in `OUTPUT` tab.

**Comment by jneira** [comment]
@MuratOzsoyler could you try again installing latest master? feel free to reopen if you continue experiencing the issue.
